trigger:
- Munish_Bug_Issue_4

pool:
  name: 'Default'

stages:
  - stage: Client
    displayName: 'Client Build and Test'
    jobs:
      - job: BuildAndTest_Client
        displayName: 'Build and Test Client'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Install Node.js'
          - task: SonarQubePrepare@4
            inputs:
              SonarQube: 'Naveed'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'GroupProjectDevops_NaveedDanish_COMP308Lab3_-Ex1_AY7s_AwSaNNkVK58z1pc'
              projectName: 'main'
          - powershell: |
              $params = "$env:SONARQUBE_SCANNER_PARAMS" -replace '"sonar.branch.name":"[\w/,-.]*"\,?'
              Write-Host "##vso[task.setvariable variable=SONARQUBE_SCANNER_PARAMS]$params"
          - script: |
              cd C:\Semester_6\Emerging_Technologies\NaveedDanish_COMP308Lab3_ Ex1\NaveedDanish_COMP308Lab3_ Ex1\client\vitalsign-app
              npm install
              npm run build
            displayName: 'Build Client'
          - task: SonarQubeAnalyze@4
          - task: SonarQubePublish@4
            inputs:
              pollingTimeoutSec: '300'
          - script: |
              cd C:\Semester_6\Emerging_Technologies\NaveedDanish_COMP308Lab3_ Ex1\NaveedDanish_COMP308Lab3_ Ex1\client\vitalsign-app
              npm install
              # Add any client-specific test commands here
            displayName: 'Run Client Tests'

  - stage: Server
    displayName: 'Server Build and Test'
    jobs:
      - job: BuildAndTest_Server
        displayName: 'Build and Test Server'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Install Node.js'

          - task: SonarQubePrepare@4
            inputs:
              SonarQube: 'Naveed'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'GroupProjectDevops_NaveedDanish_COMP308Lab3_-Ex1_AY7s_AwSaNNkVK58z1pc'
              projectName: 'main'
          - powershell: |
              $params = "$env:SONARQUBE_SCANNER_PARAMS" -replace '"sonar.branch.name":"[\w/,-.]*"\,?'
              Write-Host "##vso[task.setvariable variable=SONARQUBE_SCANNER_PARAMS]$params"
          - script: |
              cd C:\Semester_6\Emerging_Technologies\NaveedDanish_COMP308Lab3_ Ex1\NaveedDanish_COMP308Lab3_ Ex1\server
              npm install
              # Add any server-specific build commands here
            displayName: 'Build Server'
          - task: SonarQubeAnalyze@4
          - task: SonarQubePublish@4
            inputs:
              pollingTimeoutSec: '300'
          - script: |
              cd C:\Semester_6\Emerging_Technologies\NaveedDanish_COMP308Lab3_ Ex1\NaveedDanish_COMP308Lab3_ Ex1\server
              npm install
              # Add any server-specific test commands here
            displayName: 'Run Server Tests'

  - stage: Deliver
    displayName: 'Deliver Stage'
    jobs:
      - job: Deliver
        displayName: 'Deliver Artifact'
        steps:
          # Add steps for releasing your artifact
          - script: echo "Releasing the artifact"

  - stage: Deploy_to_Dev_Env
    displayName: 'Deploy to Dev Env Stage'
    jobs:
      - deployment: Deploy_to_Dev
        displayName: 'Deploy to Dev Environment'
        environment: 'Dev'
        strategy:
          runOnce:
            deploy:
              steps:
                # Placeholder steps for deploying to Dev environment
                - script: echo "Deploying to Dev environment"
                - script: echo "Launching the deployed app in Dev environment"

  - stage: Deploy_to_QAT_Env
    displayName: 'Deploy to QAT Env Stage'
    jobs:
      - deployment: Deploy_to_QAT
        displayName: 'Deploy to QAT Environment'
        environment: 'QAT'
        strategy:
          runOnce:
            deploy:
              steps:
                # Placeholder steps for deploying to QAT environment
                - script: echo "Deploying to QAT environment"

  - stage: Deploy_to_Staging_Env
    displayName: 'Deploy to Staging Env Stage'
    jobs:
      - deployment: Deploy_to_Staging
        displayName: 'Deploy to Staging Environment'
        environment: 'Staging'
        strategy:
          runOnce:
            deploy:
              steps:
                # Placeholder steps for deploying to Staging environment
                - script: echo "Deploying to Staging environment"

  - stage: Deploy_to_Production_Env
    displayName: 'Deploy to Production Env Stage'
    jobs:
      - deployment: Deploy_to_Production
        displayName: 'Deploy to Production Environment'
        environment: 'Production'
        strategy:
          runOnce:
            deploy:
              steps:
                # Placeholder steps for deploying to Production environment
                - script: echo "Deploying to Production environment"